### ISSUE TITLE
Great, but 1 need at minimum...

### ISSUE THREAD

**Issue by theperfectwill** [majid4466/concat_all#1]
Hi, this is great. It is a very solid and super light plugin. 

I added my own minification function quickly to test results. 

But a few things I see are needed at a minimum.

Can you add support for some api to delete files when needed? 
- I don't see any call for deleting files?
- In my test, files generated are never deleted. Even if I delete the page or post the files are not deleted. then there is no way to clear the cache? This leaves unneeded files on the server of course, which is why I say at a minimum this would be needed. 

If you give me something to work with I can work on improving over time. Even just a simple clear cache link on the plugin's page for the plugin next to the deactivate link. 

Thoughts?

**Comment by majid4466** [comment]
Hi!
Sorry for the late reply. Unfortunately, I don't have much free time these days. Thanks for the feedback though. I will eventually add this and other functionalities to the plugin.

**Comment by theperfectwill** [comment]
Ok. Thanks. 

Appreciate it and the response mate. Cheers!
